In [18]:
import os
import pandas as pd
import plotly.express as px

In [3]:
df = pd.read_csv(r".\Data\CA_wildfires.csv")
df.head(5)

,attr_IncidentName,poly_Acres_AutoCalc,attr_FireCauseGeneral,attr_FireDiscoveryDateTime,attr_FireOutDateTime,attr_InitialLatitude,attr_InitialLongitude,attr_InitialResponseDateTime,attr_POOCounty,attr_POOState,attr_PredominantFuelGroup
0,DIXIE,963401.766520,NaN,2021/07/14 00:15:02+00,NaN,39.876000,-121.378833,NaN,Plumas,US-CA,NaN
1,DOE,590558.481159,NaN,2020/08/16 15:48:00+00,2022/10/31 19:12:00+00,39.765360,-122.673400,2020/08/16 16:09:59+00,Glenn,US-CA,Grass-Shrub
2,DONT USE 1,390647.255518,NaN,2020/08/16 23:37:28+00,NaN,37.109676,-121.638571,NaN,Santa Clara,US-CA,NaN
3,CREEK,380561.120304,NaN,2020/09/05 01:33:00+00,2021/02/22 08:00:00+00,37.195740,-119.263800,2020/09/05 01:44:00+00,Fresno,US-CA,Timber
4,HOPKINS,328991.162338,NaN,2020/08/18 01:01:49+00,2022/10/31 20:56:00+00,40.125510,-123.073100,2020/08/18 15:59:59+00,Trinity,US-CA,Brush

In [4]:
df.shape

(1227, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1227 entries, 0 to 1226
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   attr_IncidentName             1227 non-null   object
 1   poly_Acres_AutoCalc           1151 non-null   float64
 2   attr_FireCauseGeneral         238 non-null    object
 3   attr_FireDiscoveryDateTime    1227 non-null   object
 4   attr_FireOutDateTime          824 non-null    object
 5   attr_InitialLatitude          1073 non-null   float64
 6   attr_InitialLongitude         1073 non-null   float64
 7   attr_InitialResponseDateTime  694 non-null    object
 8   attr_POOCounty                1227 non-null   object
 9   attr_POOState                 1227 non-null   object
 10  attr_PredominantFuelGroup     817 non-null    object
dtypes: float64(3), object(8)
memory usage: 105.6+ KB

In [15]:
colToDrop = [
    'attr_IncidentName', 'attr_FireCauseGeneral', 'attr_InitialResponseDateTime', 'attr_PredominantFuelGroup'
]

cleanedDF = df.drop(colToDrop, axis=1).drop_duplicates()

cleanedDF['attr_FireDiscoveryDateTime'] = cleanedDF['attr_FireDiscoveryDateTime'].str[:10]
cleanedDF["attr_FireDiscoveryDateTime"] = pd.to_datetime(cleanedDF["attr_FireDiscoveryDateTime"])

cleanedDF['attr_FireOutDateTime'] = cleanedDF['attr_FireOutDateTime'].str[:10]
cleanedDF["attr_FireOutDateTime"] = pd.to_datetime(cleanedDF["attr_FireOutDateTime"])

cleanedDF.head(5)

,poly_Acres_AutoCalc,attr_FireDiscoveryDateTime,attr_FireOutDateTime,attr_InitialLatitude,attr_InitialLongitude,attr_POOCounty,attr_POOState
0,963401.766520,2021-07-14,NaT,39.876000,-121.378833,Plumas,US-CA
1,590558.481159,2020-08-16,2022-10-31,39.765360,-122.673400,Glenn,US-CA
2,390647.255518,2020-08-16,NaT,37.109676,-121.638571,Santa Clara,US-CA
3,380561.120304,2020-09-05,2021-02-22,37.195740,-119.263800,Fresno,US-CA
4,328991.162338,2020-08-18,2022-10-31,40.125510,-123.073100,Trinity,US-CA

In [16]:
cleanedDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1227 entries, 0 to 1226
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   poly_Acres_AutoCalc         1151 non-null   float64
 1   attr_FireDiscoveryDateTime  1227 non-null   datetime64[ns]
 2   attr_FireOutDateTime        824 non-null    datetime64[ns]
 3   attr_InitialLatitude        1073 non-null   float64
 4   attr_InitialLongitude       1073 non-null   float64
 5   attr_POOCounty              1227 non-null   object
 6   attr_POOState               1227 non-null   object
dtypes: datetime64[ns](2), float64(3), object(2)
memory usage: 76.7+ KB

In [17]:
cleanedDF.to_csv('cleaned_wildfire.csv')

#Add function that moves file to data folder